/**
 * Filesystem path helpers for Pinboard assets.
 *
 * `uploads/` holds reference images (user-added or Pinterest).
 * `downloads/` holds images generated by ImageEngine, pulled down locally so
 * the TUI can render them through the same path-based ImageThumb flow.
 */

import { existsSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

export const UPLOADS_DIR = resolve(import.meta.dir, "../../../uploads");
export const DOWNLOADS_DIR = resolve(import.meta.dir, "../../../downloads");

export function ensureUploadsDir(): string {
	if (!existsSync(UPLOADS_DIR)) mkdirSync(UPLOADS_DIR, { recursive: true });
	return UPLOADS_DIR;
}

export function ensureDownloadsDir(): string {
	if (!existsSync(DOWNLOADS_DIR)) mkdirSync(DOWNLOADS_DIR, { recursive: true });
	return DOWNLOADS_DIR;
}

/**
 * Detect PNG vs JPEG from the first few bytes. ImageEngine only emits those
 * two formats (`systems/image-engine/src/routes/generate.ts`).
 */
export function detectImageExt(buf: Buffer): "png" | "jpg" {
	if (
		buf.length >= 8 &&
		buf[0] === 0x89 &&
		buf[1] === 0x50 &&
		buf[2] === 0x4e &&
		buf[3] === 0x47
	) {
		return "png";
	}
	if (buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) {
		return "jpg";
	}
	return "png";
}
